# Generated by Django 4.1.1 on 2022-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='myvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
